= T3 ([.line-through]#Takashno# Through-Test-Tool)
:toc:

== Overview
テストの効率化を目的とした扱いやすい(自分にとって)テストツールです。 +
テストシナリオをYAMLに記載し、ツールに与えることでテストを走行させるというもの。 +
また、このツールはキーワード駆動テストを行うための手段として用いれるようにすることを目標としている。 +
最終的には「ISO/IEC/IEEE 29119-5:2016」に準拠したソフトウェアを作成したいと考えている。


== Functions

* テストエンジン
* テスト管理コンソール（WEBアプリケーション）
* シナリオオーサリングツール
* 独自カスタマイズ


== Defines

* テストシナリオ管理方法
** 推奨するバージョン管理方法（Gitベース）

== YAML Structure

[source, yaml]
----
# ツールバージョン
t3 : 1.0
type : {scenario|parts|config}
# 情報
info :
   version : {scenario_version}
   id : {scenario_id|parts_id}
   summary: {scenario_summary|scenario_summary}
   description: {scenario_description|scenario_description}

# 処理フロー
flows :
  - ref : {reference scenario_process_id}
    type : {scenario|process}
    # 引数定義
    args :
      # キー：値として定義する
      - {name} : {value}
    # 結果定義（変数としてストアする）
    result :
      # キー：変数名として定義する
      - {name} : {variable_name}

# 処理定義（前後処理・実行・エビデンス取得・アサート）
processes :
  - id : {scenario_process_id}
    summary : {scenario_process_summary}
    description : {scenario_process_description}
    command : {command}
    # 以降はコマンドによって異なる

############################################################
#    # 外部コマンド参照を行う場合
#    ref :
#      id : {reference scenario_component_id}
#      # 引数定義
#      args :
#        # キー：値として定義する
#        - {name} : {value}
#      # 結果定義（変数としてストアする）
#      results :
#        # キー：変数名として定義する
#        - {name} : {variable_name}
############################################################

# 変数
variables :
  # 全体変数
  global :
    {name} : {initial_value}
  # メインシナリオ内変数
  scenario :
    {name} : {initial_value}
  # ファイル内変数
  local :
    {name} : {initial_value}

# プロファイル定義
profiles :
  # プロファイル名
  {profile_name} :
    # キー：値として定義する
    {name} : {value}

# カスタム定義
customs :
  command :
    # カスタム機能名とカスタム機能を作成したパッケージをキー：値として定義する
    {custom_name} : {package}

#
definitions :


----

上記構造は、ファイルに記載できる全ての要素となっている。 +
実際はファイルを分割し、用途毎に作成する。

=== 変数
==== 概要
動的な値を解決するために変数が必要となる。 +
シナリオを動かすにあたり、動的な値を変数に設定する。 +
そしてその後に変数の値を利用するといったもの。

==== 定義方法
変数には、有効範囲を示すスコープ概念が存在する。 +
スコープは以下の２つから選択を行う。




==== 利用方法



== Directory Structure

----
root
 |
 |-- parts
 |     |
 |     `-- {parts_id}
 |           |-- parts.yaml (ex: {parts_id}.yaml)
 |           |-- data
 |           |     |-- excel_data.xlsx
 |           |     `-- etc...
 |           `-- assert
 |                 |-- excel_data.xlsx
 |                 `-- etc...
 |
 |-- scenarios
 |     |
 |     `-- {scenario_id}
 |           |-- scenario.yaml (ex: {scenario_id}.yaml)
 |           |-- data
 |           |     |-- excel_data.xlsx
 |           |     `-- etc...
 |           `-- assert
 |                 |-- excel_data.xlsx
 |                 `-- etc...
 |-- profiles
 |     |
 |     `-- profile.yaml or {profile_name}.yaml
 |
 |
 `-- definitions
       |
       `-- {definitions}

----


== テストに必要となる機能

[option=header, cols="20,30,70"]
|====

|種別
|名称
|概要

|前・後処理
|ファイルコピー
|ファイルをコピーする機能

|前・後処理
|SQL実行機能
|任意のSQLファイルを指定されたDBに大して実行する機能

|前・後処理
|テーブルインポート機能
|ExcelもしくはCSVファイルの内容でデータベースを置き換える機能

|前・後処理
|テーブルエクスポート機能
|ExcelもしくはCSVファイルの内容でデータベースを置き換える機能

|実行
|WEB操作機能
|SeleniumによるWEBブラウザの操作機能

|実行
|REST-API実行機能
|任意のREST-APIの実行機能




|====

== 実行結果

----
root
 |
 |-- YYYYMMDD_HHMMSS_{scenario_id}
 |     |
 |     |-- result.html 結果となるHTMLレポート
 |     `-- evidences
 |           |
 |           `-- {reference scenario_process_id}
 |                 |-- *.log
 |                 `-- etc...
----