= T3 ([.line-through]#Takashno# Through-Test-Tool)
:toc:

== Overview
テストの効率化を目的とした扱いやすい(自分にとって)テストツールです。 +
テストシナリオをYAMLに記載し、ツールに与えることでテストを走行させるというもの。 +
また、このツールはキーワード駆動テストを行うための手段として用いれるようにすることを目標としている。 +
最終的には「ISO/IEC/IEEE 29119-5:2016」に準拠したソフトウェアを作成したいと考えている。


== Functions

* テストエンジン
* テスト管理コンソール（WEBアプリケーション）
* シナリオオーサリングツール
* 独自カスタマイズ


== Defines

* テストシナリオ管理方法
** 推奨するバージョン管理方法（Gitベース）

== YAML Structure

[source, yaml]
----
# ツールバージョン
t3 : 1.0
type : {scenario|parts|config}
# 情報
info :
   version : {scenario_version}
   id : {scenario_id|parts_id}
   summary: {scenario_summary|scenario_summary}
   description: {scenario_description|scenario_description}

# 処理フロー
flows :
  - ref : {reference scenario_process_id}
    type : {scenario|process}
    # 引数定義
    args :
      # キー：値として定義する
      - {name} : {value}
    # 結果定義（変数としてストアする）
    result :
      # キー：変数名として定義する
      - {name} : {variable_name}

# 処理定義（前後処理・実行・エビデンス取得・アサート）
processes :
  - id : {scenario_process_id}
    summary : {scenario_process_summary}
    description : {scenario_process_description}
    command : {command}
    # 以降はコマンドによって異なる

############################################################
#    # 外部コマンド参照を行う場合
#    ref :
#      id : {reference scenario_component_id}
#      # 引数定義
#      args :
#        # キー：値として定義する
#        - {name} : {value}
#      # 結果定義（変数としてストアする）
#      results :
#        # キー：変数名として定義する
#        - {name} : {variable_name}
############################################################

# 変数
variables :
  # 全体変数
  global :
    {name} : {initial_value}
  # メインシナリオ内変数
  scenario :
    {name} : {initial_value}
  # ファイル内変数
  local :
    {name} : {initial_value}

# プロファイル定義
profiles :
  # プロファイル名
  {profile_name} :
    # キー：値として定義する
    {name} : {value}

# カスタム定義
customs :
  command :
    # カスタム機能名とカスタム機能を作成したパッケージをキー：値として定義する
    {custom_name} : {package}

#
definitions :


----

上記構造は、ファイルに記載できる全ての要素となっている。 +
実際はファイルを分割し、用途毎に作成する。

=== 変数
==== 概要
動的な値を解決するために変数が必要となる。 +
シナリオを動かすにあたり、動的な値を変数に設定する。 +
そしてその後に変数の値を利用するといったもの。

==== 定義方法
変数には、有効範囲を示すスコープ概念が存在する。 +
スコープは以下の２つから選択を行う。




==== 利用方法



== Directory Structure

----
root
 |
 |-- parts
 |     |
 |     `-- {parts_id}
 |           |-- parts.yaml (ex: {parts_id}.yaml)
 |           |-- data
 |           |     |-- excel_data.xlsx
 |           |     `-- etc...
 |           `-- assert
 |                 |-- excel_data.xlsx
 |                 `-- etc...
 |
 |-- scenarios
 |     |
 |     `-- {scenario_id}
 |           |-- scenario.yaml (ex: {scenario_id}.yaml)
 |           |-- data
 |           |     |-- excel_data.xlsx
 |           |     `-- etc...
 |           `-- assert
 |                 |-- excel_data.xlsx
 |                 `-- etc...
 |-- profiles
 |     |
 |     `-- profile.yaml or {profile_name}.yaml
 |
 |
 `-- definitions
       |
       `-- {definitions}

----


== テストに必要になるプロセス

.分類一覧
[option=header, cols="30,70"]
|====

|分類
|概要

|ファイルシステム操作
|ファイルシステムについての操作機能

|WEB操作機能
|SeleniumによるWEBブラウザの操作機能


|====

.プロセス一覧
[option=header, cols="30,30,50,70"]
|====

|分類1
|分類2
|名称
|概要

|ファイルシステム操作
|-
|ファイルコピー
|ファイルをコピーする機能。

|ファイルシステム操作
|-
|ファイル削除
|ファイルを削除する機能。

|ファイルシステム操作
|-
|ファイル移動
|ファイルを移動する機能。

|ファイルシステム操作
|-
|ディレクトリクリア
|ディレクトリ配下に存在するファイルを削除して空の状態にする機能。

|ファイルシステム操作
|-
|ディレクトリ作成
|ディレクトリを作成する。

|ファイルシステム操作
|-
|ディレクトリ削除
|ディレクトリを削除する。

|データベース操作
|-
|SQL実行機能
|任意のSQLファイルを指定されたDBに大して実行する機能

|データベース操作
|-
|テーブルインポート機能
|ExcelもしくはCSVファイルの内容でデータベースを置き換える機能

|データベース操作
|エビデンス取得
|テーブルエクスポート機能
|ExcelもしくはCSVファイルの内容でデータベースを置き換える機能


|WEB操作機能
|-
|テキスト入力
|HTMLの入力テキストに対して入力を行う。

|WEB操作機能
|-
|要素クリック
|ボタン等の任意のHTMLの要素をクリックする。

|WEB操作機能
|-
|プルダウン選択
|指定したプルダウンの指定した要素を選択する。

|WEB操作機能
|エビデンス取得機能
|画面スナップショット取得
|ブラウザで表示中のスナップショットを取得する機能。

|WEB操作機能
|エビデンス取得機能
|HTML取得
|ブラウザで表示中のHTMLのソースコードを取得する機能。

|HTTP通信機能
|エビデンス取得機能
|REST-API実行機能
|任意のREST-APIの実行機能

|アサート機能
|-
|テキストファイル - 文字列存在判定
|指定したテキストファイルに、指定した文字列が存在することを判定する機能

|アサート機能
|-
|テキストファイル - 文字列非存在判定
|指定したテキストファイルに、指定した文字列が存在しないことを判定する機能

|アサート機能
|-
|ファイル存在判定
|指定されたファイルがファイルシステム上に存在することを判定する機能

|アサート機能
|-
|ファイル非存在判定
|指定されたファイルがファイルシステム上に存在することを判定する機能

|アサート機能
|-
|ファイル非存在判定
|指定されたファイルがファイルシステム上に存在することを判定する機能

|====

== 実行結果

----
root
 |
 |-- YYYYMMDD_HHMMSS_{scenario_id}
 |     |
 |     |-- result.html 結果となるHTMLレポート
 |     `-- evidences
 |           |
 |           `-- {reference scenario_process_id}
 |                 |-- *.log
 |                 `-- etc...
----